### ISSUE TITLE
Enforce IP ACL for machine boot requests

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/epoxy#42]
The epoxy server is designed to restrict boot requests to the machine IP address. To assist with development, to date, the sandbox and staging deployments have not been applied this restriction.

This Story should complete the IP whitelist filter and include the option for administrative and diagnostic requests from trusted sources.

**Comment by pboothe** [comment]
As done as it can be until PLC upgrades are complete.

**Comment by mehtab11** [comment]
Update?

**Comment by stephen-soltesz** [comment]
Fixing it now.
